### PR TITLE
[i18n]Add Simplified Chinese translation support.

### PR DESCRIPTION
**Pull request by h404bi**
For version 1.2. It has been tested on my private server and works fine.

### CODE REVIEW

**Comment by AmauryCarrade** [comment]
Thanks! I'll just wait for the build to complete, just to be sure :) .

**Comment by h404bi** [comment]
wrong target branch, sorry.

**Comment by AmauryCarrade** [comment]
Why? I merge everything on the `dev` branch excepted for releases.

**Comment by h404bi** [comment]
Em, this is for v1.2, then I will open a new pull request on branch dev. I notice that there are some changes between these two branch's translation. I think users can use the zh_CN translation before you release new stable version. :-)

**Pull request closed without merging**
